[package]
name = "meow-vm-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Adapter that executes MEOW smart contracts against the blockchain state"

[dependencies]
bcs.workspace = true
rand.workspace = true
serde.workspace = true
thiserror.workspace = true

meow-types.workspace = true
meow-vm.workspace = true
meow-vm-bytecode-verifier.workspace = true
meow-vm-compiler.workspace = true
meow-vm-types.workspace = true

[dev-dependencies]
tokio.workspace = true

# Cycle dev dependencies are allowed,
# but pay attention that `meow-framework` depends on `meow-vm-adapter`.
meow-framework.workspace = true
