[package]
name = "meow-vm-adapter"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Valerii Reutov <valeriy.reutov@gmail.com>"]

[features]
testing = []

[dependencies]
bcs.workspace = true
thiserror.workspace = true
serde.workspace = true

meow-types.workspace = true
meow-vm.workspace = true
