[package]
name = "meow-vm-adapter"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Valerii Reutov <valeriy.reutov@gmail.com>"]
description = "Adapter that executes MEOW smart contracts against the blockchain state"

[dependencies]
bcs.workspace = true
thiserror.workspace = true
serde.workspace = true

meow-types.workspace = true
meow-vm.workspace = true
meow-vm-compiler.workspace = true
meow-vm-types.workspace = true
