[package]
name = "meow-gossip-network"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "libp2p gossip-based peer-to-peer network layer"

[dependencies]
futures.workspace = true
libp2p.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

meow-gossip-types.workspace = true
