[package]
name = "meow-nakamoto-types"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Nakamoto-consensus types — block, block header, etc."

[dependencies]
bcs.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

meow-genesis.workspace = true
meow-types.workspace = true
meow-vm-adapter.workspace = true
