[package]
name = "meow-genesis"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Genesis block construction and initial allocation processing"

[dependencies]
serde.workspace = true
thiserror.workspace = true

meow-framework.workspace = true
meow-types.workspace = true
meow-vm-adapter.workspace = true
