[package]
name = "meow-vm"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Valerii Reutov <valeriy.reutov@gmail.com>"]
description = "Stack-based virtual machine for executing MEOW smart contracts"

[dependencies]
bcs.workspace = true
thiserror.workspace = true
serde.workspace = true

meow-vm-types.workspace = true

[dev-dependencies]
meow-vm-compiler.workspace = true
