[package]
name = "meow-node-client"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Valerii Reutov <valeriy.reutov@gmail.com>"]
description = "HTTP client for the MEOW node API"

[dependencies]
reqwest = { version = "0.13", features = ["json"] }

thiserror.workspace = true
url.workspace = true

meow-types.workspace = true
