[package]
name = "meow-framework"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Valerii Reutov <valeriy.reutov@gmail.com>"]
description = "Built-in standard library modules for the MEOW VM"

[dependencies]
bcs.workspace = true

meow-types.workspace = true
meow-vm-adapter.workspace = true
meow-vm-types.workspace = true
