[package]
name = "meow-framework"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Built-in standard library modules for the MEOW VM"

[dependencies]
bcs.workspace = true

meow-types.workspace = true
meow-vm-adapter.workspace = true
meow-vm-types.workspace = true
