[package]
name = "meow-types"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Core MEOW blockchain types — transactions, objects, addresses, and keys"

[dependencies]
ed25519-consensus = "2.1"
slip10_ed25519 = "0.1"
tiny-bip39 = "2.0"
zeroize = { version = "1.8", features = ["derive"] }

base64.workspace = true
bcs.workspace = true
bip32.workspace = true
blake2.workspace = true
bs58.workspace = true
dirs.workspace = true
hex.workspace = true
prefix-hex.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true

meow-vm-types.workspace = true

[dev-dependencies]
temp-dir.workspace = true
temp-env = "0.3"
