[package]
name = "meow-types"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Valerii Reutov <valeriy.reutov@gmail.com>"]
description = "Core MEOW blockchain types — transactions, objects, addresses, and keys"

[dependencies]
ed25519-consensus = "2.1.0"
slip10_ed25519 = "0.1.3"
tiny-bip39 = "2.0.0"
zeroize = { version = "1.8.1", features = ["derive"] }

base64.workspace = true
bcs.workspace = true
bip32.workspace = true
blake2.workspace = true
bs58.workspace = true
dirs.workspace = true
hex.workspace = true
prefix-hex.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true

meow-vm-types.workspace = true

[dev-dependencies]
temp-dir.workspace = true
temp-env = "0.3"
