[package]
name = "meow-node"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Valerii Reutov <valeriy.reutov@gmail.com>"]
description = "meow-node is a MEOW network node"

[dependencies]
axum = "0.8"

anyhow.workspace = true
bcs.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

meow-gossip-network.workspace = true
meow-nakamoto.workspace = true
meow-types.workspace = true
