use meow_types::{address::Address, digest::Digest};
use meow_vm::types::Value;

/// Tracks side effects of native function calls during execution.
pub struct Context {
    /// Sender address (from the transaction).
    sender: Address,
    /// Transaction digest bytes (used for fresh ID derivation).
    tx_digest: Digest,
    /// Counter for deriving unique fresh object IDs.
    id_counter: u64,
    /// IDs generated by meow_vm_fresh_id (must all be accounted for).
    fresh_ids: Vec<Address>,
    /// Objects transferred out: (object_value, new_owner_address).
    transfers: Vec<(Value, Address)>,
    /// Objects destroyed.
    destroyed: Vec<Value>,
}

impl Context {
    /// Create a new execution context for a transaction.
    pub fn new(sender: Address, tx_digest: Digest) -> Self {
        Self {
            sender,
            tx_digest,
            id_counter: 0,
            fresh_ids: Vec::new(),
            transfers: Vec::new(),
            destroyed: Vec::new(),
        }
    }

    /// Get the sender address.
    pub fn sender(&self) -> Address {
        self.sender
    }

    /// Get the list of fresh IDs generated during execution.
    pub fn fresh_ids(&self) -> &[Address] {
        &self.fresh_ids
    }

    /// Get the list of transferred objects and their new owners.
    pub fn transfers(&self) -> &[(Value, Address)] {
        &self.transfers
    }

    /// Get the list of destroyed objects.
    pub fn destroyed(&self) -> &[Value] {
        &self.destroyed
    }

    /// Derives a fresh object ID from the transaction digest and a counter.
    pub fn next_fresh_id(&mut self) -> Address {
        let address = Address::derive(self.tx_digest, 0u8, self.id_counter);

        self.fresh_ids.push(address);
        self.id_counter += 1;

        address
    }

    /// Record an object transfer to a new owner.
    pub fn transfer(&mut self, obj: Value, new_owner: Address) {
        self.transfers.push((obj, new_owner));
    }

    /// Record an object destruction.
    pub fn destroy(&mut self, obj: Value) {
        self.destroyed.push(obj);
    }
}
