use meow_types::{address::Address, digest::Digest};
use meow_vm_types::types::Value;
use rand::{RngCore, SeedableRng, rngs::StdRng};

use crate::external_context::{DEFAULT_RAND_SEED, RandSeed};

/// Tracks side effects of native function calls during execution.
pub struct Context {
    /// Sender address (from the transaction).
    sender: Address,
    /// Transaction digest bytes (used for fresh ID derivation).
    tx_digest: Digest,
    /// Counter for deriving unique fresh object IDs.
    id_counter: u64,
    /// IDs generated by meow_vm_fresh_id (must all be accounted for).
    fresh_ids: Vec<Address>,
    /// Objects transferred out: (object_value, new_owner_address).
    transfers: Vec<(Value, Address)>,
    /// Objects destroyed.
    destroyed: Vec<Value>,
    /// Random number generator (needed for native functions that require randomness).
    random_generator: rand::rngs::StdRng,
    /// Block timestamp (Unix milliseconds) at the time the block was mined.
    timestamp: u64,
}

impl Context {
    /// Creates a new execution context for a transaction.
    pub fn new(sender: Address, tx_digest: Digest, rand_seed: RandSeed, timestamp: u64) -> Self {
        Self {
            sender,
            tx_digest,
            id_counter: 0,
            fresh_ids: Vec::new(),
            transfers: Vec::new(),
            destroyed: Vec::new(),
            random_generator: create_random_generator(tx_digest, rand_seed),
            timestamp,
        }
    }

    /// Get the sender address.
    pub fn sender(&self) -> Address {
        self.sender
    }

    /// Get the list of fresh IDs generated during execution.
    pub fn fresh_ids(&self) -> &[Address] {
        &self.fresh_ids
    }

    /// Get the list of transferred objects and their new owners.
    pub fn transfers(&self) -> &[(Value, Address)] {
        &self.transfers
    }

    /// Get the list of destroyed objects.
    pub fn destroyed(&self) -> &[Value] {
        &self.destroyed
    }

    /// Derives a fresh object ID from the transaction digest and a counter.
    pub fn next_fresh_id(&mut self) -> Address {
        let address = Address::derive(self.tx_digest, 0, self.id_counter);

        self.fresh_ids.push(address);
        self.id_counter += 1;

        address
    }

    /// Record an object transfer to a new owner.
    pub fn transfer(&mut self, obj: Value, new_owner: Address) {
        debug_assert!(
            matches!(obj, Value::Object { .. }),
            "Only object values can be transferred"
        );
        self.transfers.push((obj, new_owner));
    }

    /// Record an object destruction.
    pub fn destroy(&mut self, obj: Value) {
        debug_assert!(
            matches!(obj, Value::Object { .. }),
            "Only object values can be destroyed"
        );
        self.destroyed.push(obj);
    }

    /// Get the next pseudo-random `u64` from the transaction's RNG sequence.
    pub fn next_rand(&mut self) -> u64 {
        self.random_generator.next_u64()
    }

    /// Returns the block timestamp (Unix milliseconds) at the time the block was mined.
    pub fn timestamp(&self) -> u64 {
        self.timestamp
    }
}

impl Default for Context {
    fn default() -> Self {
        Self::new(Address::ZERO, Digest::ZERO, DEFAULT_RAND_SEED, 0)
    }
}

/// Create a random generator seeded from the transaction digest and random seed.
fn create_random_generator(tx_digest: Digest, rand_seed: RandSeed) -> StdRng {
    let mut signable = tx_digest.as_ref().to_vec();
    signable.extend_from_slice(&rand_seed);

    let seed = Digest::compute(&signable).expect("Failed to compute a seed for random generator");

    StdRng::from_seed(seed.into())
}

#[cfg(test)]
mod tests {
    use meow_types::{address::Address, digest::Digest};
    use meow_vm_types::types::Value;

    use crate::external_context::DEFAULT_RAND_SEED;

    use super::Context;

    const SENDER: Address = Address::fill(0xAA);

    #[test]
    fn initial_state_is_empty() {
        let ctx = make_ctx();
        assert!(ctx.fresh_ids().is_empty());
        assert!(ctx.transfers().is_empty());
        assert!(ctx.destroyed().is_empty());
    }

    #[test]
    fn sender_returns_correct_address() {
        let ctx = make_ctx();
        assert_eq!(ctx.sender(), SENDER);
    }

    #[test]
    fn fresh_ids_are_unique() {
        let mut ctx = make_ctx();
        let id0 = ctx.next_fresh_id();
        let id1 = ctx.next_fresh_id();
        assert_ne!(id0, id1);
    }

    #[test]
    fn fresh_ids_are_recorded_in_order() {
        let mut ctx = make_ctx();
        let id0 = ctx.next_fresh_id();
        let id1 = ctx.next_fresh_id();
        assert_eq!(ctx.fresh_ids(), &[id0, id1]);
    }

    #[test]
    fn fresh_ids_are_deterministic() {
        let mut ctx1 = make_ctx();
        let mut ctx2 = make_ctx();
        assert_eq!(ctx1.next_fresh_id(), ctx2.next_fresh_id());
        assert_eq!(ctx1.next_fresh_id(), ctx2.next_fresh_id());
    }

    #[test]
    fn transfer_is_recorded() {
        let mut ctx = make_ctx();
        let owner = Address::fill(2);
        ctx.transfer(test_object(), owner);
        assert_eq!(ctx.transfers().len(), 1);
        assert_eq!(ctx.transfers()[0].1, owner);
    }

    #[test]
    fn destroy_is_recorded() {
        let mut ctx = make_ctx();
        ctx.destroy(test_object());
        assert_eq!(ctx.destroyed().len(), 1);
    }

    fn test_object() -> Value {
        Value::Object {
            type_name: "MeowCoin".to_string(),
            fields: vec![
                ("id".to_string(), Value::Address([1; 32])),
                ("balance".to_string(), Value::U64(100)),
            ],
        }
    }

    #[test]
    fn rand_values_are_deterministic() {
        let mut ctx1 = make_ctx();
        let mut ctx2 = make_ctx();
        assert_eq!(ctx1.next_rand(), ctx2.next_rand());
        assert_eq!(ctx1.next_rand(), ctx2.next_rand());
    }

    #[test]
    fn rand_advances_per_call() {
        let mut ctx = make_ctx();
        let v1 = ctx.next_rand();
        let v2 = ctx.next_rand();
        assert_ne!(v1, v2, "successive rand calls must return different values");
    }

    #[test]
    fn different_seeds_produce_different_rand_values() {
        let mut ctx1 = Context::new(SENDER, Digest::ZERO, [1u8; 32], 0);
        let mut ctx2 = Context::new(SENDER, Digest::ZERO, [2u8; 32], 0);
        assert_ne!(
            ctx1.next_rand(),
            ctx2.next_rand(),
            "different seeds must produce different random values"
        );
    }

    fn make_ctx() -> Context {
        Context::new(SENDER, Digest::ZERO, DEFAULT_RAND_SEED, 0)
    }
}
